### ISSUE TITLE
Reusing existing NATS connection from ts-nats in stan

### ISSUE THREAD

**Issue by mbaranovski** [nats-io/stan.js#116]
Hi, I'm trying to provide `nc` option when connecting to the NATS Streaming but I am getting an incorrect error `NATS connection encoding must be 'binary'` because NATS encoding is already set to `binary`.

After drilling down a bit more it turns out that in `createConnection` stan function we're checking for the encoding like this:
```
if (typeof this.options.nc === 'object') {
        if (this.options.nc.encoding !== 'binary') {
            throw new Error(BINARY_ENCODING_REQUIRED);
        } else {
            this.nc = this.options.nc;
        }
    }
```
the `this.options.nc.encoding` is undefined. This is what `this.options.nc` contains, sorry for the long copy paste:
```
Client {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  createInbox: [Function: createInbox],
  protocolHandler:
   ProtocolHandler {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     muxSubscriptions: MuxSubscriptions { reqs: {}, length: 0 },
     closed: false,
     connected: true,
     inbound: DataBuffer { buffers: [], byteLength: 0 },
     info: {},
     infoReceived: false,
     outbound: DataBuffer { buffers: [], byteLength: 0 },
     pongs: [],
     pout: 0,
     reconnecting: false,
     reconnects: 0,
     ssid: 1,
     state: 0,
     wasConnected: false,
     draining: false,
     noMorePublishing: false,
     client: [Circular],
     options:
      { encoding: 'binary',
        maxPingOut: 2,
        maxReconnectAttempts: 10,
        noRandomize: false,
        pedantic: false,
        pingInterval: 120000,
        reconnect: true,
        reconnectTimeWait: 2000,
        tls: undefined,
        verbose: false,
        waitOnFirstConnect: false,
        url: 'nats://localhost:4222',
        payload: 'binary' },
     encoding: 'binary',
     payload: 'binary',
     subscriptions:
      Subscriptions {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        subs: {},
        sidCounter: 0,
        length: 0 },
     servers: Servers { servers: [Array], currentServer: [Server] },
     transport:
      TCPTransport {
        connectedOnce: true,
        stream: [Socket],
        closed: false,
        handlers: [Object] },
     currentServer:
      Server { url: [Url], didConnect: false, reconnects: 0, implicit: false },
     url:
      Url {
        protocol: 'nats:',
        slashes: true,
        auth: null,
        host: 'localhost:4222',
        port: '4222',
        hostname: 'localhost',
        hash: null,
        search: null,
        query: null,
        pathname: null,
        path: null,
        href: 'nats://localhost:4222' },
     pingTimer:
      Timeout {
        _called: false,
        _idleTimeout: 120000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 1054,
        _onTimeout: [Function],
        _timerArgs: [Array],
        _repeat: null,
        _destroyed: false,
        [Symbol(unrefed)]: false,
        [Symbol(asyncId)]: 10,
        [Symbol(triggerId)]: 9 } } }
```

It looks like in order to get the encoding value we need to go down to the `protocolHandler` property.

Am I doing it correctly or ts-nats is not compatible with nats-streaming.

**Comment by aricart** [comment]
@mbaranovski indeed stan.js can only use nats.js for a connection.

**Comment by mbaranovski** [comment]
Any plans on adding it in the future? I'm happy to jump in and implement it if it's something worth doing. Not sure how big of a change to ts-nats that would be?

**Comment by aricart** [comment]
the idea is eventually all the js clients will use the ts-nats backend. However if you are an adopter of ts-nats, you are looking for modern javascript with promises/async/etc. Stan.js is a node evented client. I was thinking of doing a stan.ts when I get some cycles later in the year.

**Comment by Bvriens** [comment]
> indeed stan.js can only use nats.js for a connection.

@aricart with stan.js and nats.js this should work? 
Because I'm getting the same error with  stan.js and nats.js.
Could you direct me in the right direction.

Code:
`const CONFIG = require("../Config");

const NATS = require("nats");
const STAN = require("node-nats-streaming");

nats = NATS.connect(CONFIG.nats_server);

nats.on("connect", () => {
  console.log("nats connected");
  let stan = STAN.connect(CONFIG.stan_server, "job-mapping-service", {
    nc: nats
  });
});

nats.on("error", err => {
  console.log("nats error", err);
});`

error:

`nats connected
job-service_1  | /node/node_modules/node-nats-streaming/lib/stan.js:268
job-service_1  |             throw new Error(BINARY_ENCODING_REQUIRED);
job-service_1  |             ^
job-service_1  | 
job-service_1  | Error: stan: NATS connection encoding must be 'binary'.
job-service_1  |     at Stan.createConnection (/node/node_modules/node-nats-streaming/lib/stan.js:268:19)
job-service_1  |     at new Stan (/node/node_modules/node-nats-streaming/lib/stan.js:94:10)
job-service_1  |     at Object.exports.connect (/node/node_modules/node-nats-streaming/lib/stan.js:110:12)
job-service_1  |     at Client.<anonymous> (/node/src/services/MappingService.js:14:19)
job-service_1  |     at Client.emit (events.js:223:5)
job-service_1  |     at Client.connectCB (/node/node_modules/nats/lib/nats.js:631:8)
job-service_1  |     at /node/node_modules/nats/lib/nats.js:1191:20
job-service_1  |     at Client.processInbound (/node/node_modules/nats/lib/nats.js:1137:13)
job-service_1  |     at Socket.<anonymous> (/node/node_modules/nats/lib/nats.js:750:10)
job-service_1  |     at Socket.emit (events.js:223:5)
`

**Comment by aricart** [comment]
@Bvriens  you need to provide the `encoding` option 'binary'.

**Comment by Bvriens** [comment]
@aricart  Thx!
adding encoding: "binary" to the connection options of the nats server worked like a charm.
