### ISSUE TITLE
Performing a graceful shutdown of a subscriber

### ISSUE THREAD

**Issue by AaronFriel** [nats-io/stan.js#131]
It looks like from the code that closing the subscription results in a non-graceful shutdown and could result in any in flight messages being duplicated. Is there any plan to support a `gracefulClose()` or similar command that shuts down the inbox for new messages in flight while allowing all those currently being processed to be acked?

I see that both `Subscription#close` and `Subscription#unsubscribe` call `this.closeOrUnsubscribe`, defined here: 

https://github.com/nats-io/stan.js/blob/a7b43c4c7eb63627997f964df80a6c3939f0b04e/lib/stan.js#L794-L801

And we see that deleting `this.stanConnection` results in `Subscription#isClosed()` returning true:

https://github.com/nats-io/stan.js/blob/a7b43c4c7eb63627997f964df80a6c3939f0b04e/lib/stan.js#L762-L764

Which I think means that acking a message after a close will *silently* fail:

https://github.com/nats-io/stan.js/blob/a7b43c4c7eb63627997f964df80a6c3939f0b04e/lib/stan.js#L974-L981

**Comment by aricart** [comment]
@AaronFriel I have not heard of plans to have a `drain` mechanism on nats-streaming - @kozlovic may want to chime in on this.

If you think about it, nats-streaming provides at-least-one semantics, so it is OK for the client to simply close the subscriptions, flush() and close the client. If you are using queues and durable subscriptions this is even easier, since messages will resume with un-processed messages (or messages that originally were scheduled for your client, will be sent to another queue member for processing).

There are two ways of doing it:

When your application wants to close, you could send it some sort of signal. Knowing that node is event handling is synchronous, it is safe to close the the stan subscriptions and the client. Even if messages are waiting for dispatch, the event loop will be processing your handler for the signal which means that the nats-streaming subscription is not currently in flight.

From your comment I am deducing that you tried to do it from your message handler. However your subscription was not doing manual acks, so the acking of the message happens right after your handler returns, will fail as you describe. To bypass this issue, you will want to schedule the subscription close in a `process.nextTick()` or timer. Alternatively you can make your subscription do manual acks, and then ack, and close the subscription.

When you have closed all subscriptions, you should invoke a `flush` from the underlying NATS connection. This will insure that any messages outgoing from your application are sent (if not yet sent). When the flush callback returns you can safely `close`.

**Comment by kozlovic** [comment]
In Streaming there is indeed no way of draining the subscription but be able to process/ack those inflight messages. This is not only a library limitation, the server would have to understand a new protocol that would say don't send any new message but keep the subscription opened so acks for this subscription can still be processed.
Even with MaxInflight of 1, you would still get one extra message delivered because say you use manual ack mode and do ack+close, the processing of the ack will trigger a new send before the close is processed.
But as suggested, if you use queue subscriptions, all those delivered but unack'ed messages will be redelivered to other running members. For non durable subscriptions, it does not matter since the subscription goes away. For a durable subscription, the messages will be redelivered first when the durable restarts.
