### ISSUE TITLE
Help with reconnect

### ISSUE THREAD

**Issue by ronezra3** [nats-io/stan.js#134]
Thanks a lot on your last answer.
I still need some more help :)

I try this code (after your great recommendation) -

```
const STAN = require("node-nats-streaming");


const myEmitter = require('./event.js');
(() => {
    const stan = STAN.connect("test-cluster", "testid1234");
    stan.on('connect', () => {
        myEmitter.on('event', (data) => {
            stan.publish("hello", JSON.stringify(data));
        })

        const opts = stan.subscriptionOptions();
        opts.setStartWithLastReceived();
        const sub = stan.subscribe("hello", opts);
        sub.on('message', (msg) => {
            console.log(msg.getData());
        });

        stan.on('connection_lost', function (error) {
            console.log('disconnected from stan', error);
        });
    });
})()
```

I send a NodeJS event every time there is new data.

1. I get an error once in a while of "Nats error" - you what can cause it?
2. the 'connection_lost' event never fired. How I can handle the reconnect after the connection lost?

Thanks a lot!

**Comment by aricart** [comment]
@ronezra3 Could you please provide the stack trace and text from the error? You can listen for errors by registering a listener on the stan connection for the 'error' event.

As for `connection_lost` you will only get this message if the client looses connection with the server. If you are running an embedded nats-server  (you are only running nats-streaming-server) you'll likely never get the event. Some configurations have a nats-streaming-server connect to a nats-server. And since the client doesn't have a direct tcp connection to the streaming server, it is possible for the nats-streaming-server to go away. The `connnection_lost` allows your client to detect these conditions - see https://github.com/nats-io/stan.js#connection-status

**Comment by aricart** [comment]
@ronezra3 I didn't hear back on this issue, so I will close this issue. Feel free to reopen.
