### ISSUE TITLE
Keep getting NatsError: Connection closed error

### ISSUE THREAD

**Issue by sujeshthekkepatt** [nats-io/stan.js#167]
I have a Nodejs app engine instance running, which acts as both the publisher and subscriber which connects to NATS-STREAMING-SERVER running on Docker in a VM. I keep getting `NatsError: Connection closed` error. But it happening not consistently. The VM has `20GB` storage and free space of `3.5 GB`.  I don't see any error log in the docker. Any Idea why might be this happening?

**Comment by aricart** [comment]
@sujeshthekkepatt can you give me a bit more info - versions of the components etc.
Also you'll want to register listeners for `error` and `connection_lost`.

Any `NatsError` instance will have an underlying error (`.chainedError`) if there's one. 

In addition, you may want to add a listener to `connection_lost` on the stan connection to see if the connection is getting lost. This would happen if the nats-streaming-server is connecting to a different nats-server and the connection between the two is lost.

The nats-streaming server has a `-DV` option that you can use to monitor the protocol, and see if there's some information on the server as to why the client was disconnected. 
You can also run the server with `-SV` to see any messages from the streaming server.

**Comment by sujeshthekkepatt** [comment]
My server is running with the `-SDV` option. However, it didn't listen to the `connection_lost` event. Don't know what might cause that? Also the NATS-STREAMING server does not have any error logs. So from the docs, I found that when a connection is closed by the client it needs to be created and the necessary subscriptions too. Any insight on this?

**Comment by aricart** [comment]
@sujeshthekkepatt all stan clients have to re-establish their subscriptions if the client is closed for whatever reason (`close` event is raised). The `connection_lost` also raises a `close`. Note that this is only on close, if you disconnect and reconnect soon enough, the subscription will continue working. 

Now be aware that if you had messages that were pending during a disconnect (they were not sent to the server yet), those messages are lost (this includes any acknowledgment messages).

For additional information, you'll have to make sure that you have registered your `error` handlers. One thing that you can do is insure that you give a name to your client, and then [enable monitoring on the server](https://docs.nats.io/nats-server/configuration/monitoring#monitoring-nats) and for [nats-streaming monitoring](https://docs.nats.io/nats-streaming-concepts/monitoring). If you check  the [connz endpoint](https://docs.nats.io/nats-server/configuration/monitoring#connection-information) there should be a reason if the server disconnected the client for any reason. Otherwise it was something related on the client-side.

**Comment by aricart** [comment]
Finally - knowing the versions of the server/client and your connection setup (options you are passing etc) would be useful to help identify the issue.

**Comment by sujeshthekkepatt** [comment]
> Finally - knowing the versions of the server/client and your connection setup (options you are passing etc) would be useful to help identify the issue.

I am very sorry, forgot to add that. Given below my config,

```
NATS-SERVER-VERSION: 2.1.4

NATS-STREAMING-SERVER-VERSION: 0.17.0

STAN.JS VERSION(node-nats-streaming): 0.2.6 
```

I am running `NATS-STREAMING-SERVER` in a docker-compose file with options  `-SDV`. Also running monitoring ports. My Nodejs single server acts as both publisher and subscriber. Instead of making an ad-hoc connection each time for publishing, I am keeping a reference to a previously established connection(preferably in the application startup). SO far so good when this issue came (but didn't affect my application totally but some instances). So what are the effective method to register the connection? Do I have to use a connection pool on top of the lib?

**Comment by aricart** [comment]
You should be running node-nats-streaming@latest = `npm install node-nats-straeming@latest`

**Comment by aricart** [comment]
> So what are the effective method to re-register the connection? Do I have to use a connection pool on top of the lib?

Effectively if your service depends on nats-streaming-messages, then if the connection closes, you should simply exit your service and have your system process restart it. You don't need a connection pool, as messages will be redelivered to you and you can resume where you left off. Now obviously you should be aware of outgoing messages and whether they were ack'ed by the server.

**Comment by lw-mgr** [comment]
Same here. If the connection is lost to the NATS-Streaming Server, the nodejs app does not auto-recoonect.
Auto-reconnect is enabled without limit (-1) but not working as expected.

**Comment by aricart** [comment]
@lw-mgr From your description it sounds like you got a `connection_lost` notification. If that is the case:

- Reconnect affects connection to the _nats-server_. The _nats-streaming-server_ is a _client_ of the _nats-server_. This can be strange since if you are running a _nats-streaming-server_ which if by default will use an embedded _nats-server_

- if you get `connection_lost`, you need to programmatically reconnect the stan connection. The stan client will not continue after a `connection_lost`. Connection lost, means that the session with the nats-streaming-server could not be resumed - either the nats-streaming-server restarted with a memory store or something like that.
