### ISSUE TITLE
buffering messages during reconnect

### ISSUE THREAD

**Issue by sujeshthekkepatt** [nats-io/stan.js#168]
As per the https://docs.nats.io/developing-with-nats/reconnect/buffer , I see configuring reconnect buffer is not available in Javascript. But I couldn't find any docs that relevant to reconnect buffer. Does the lib supports buffering messages during reconnect ?

**Comment by aricart** [comment]
It supports buffering but may not be what you expect. - The pending buffer is honored if you publish messages after a disconnect. However any messages that were pending before the disconnect are lost. This is provided by the underlying nats.js library. Also on plain nats, all subscriptions are re-established on reconnect. On stan.js, this adds additional complexities because all operations are request-reply, so it is possible for acknowledgments from both the client and the server to be lost during the disconnect.

If you are relying on the pending buffer to assume that your outbound messages and acknowledgments are sent, it may not work out that way. For streaming your signal that the server received a message is the acknowledgments, so you should use these to determine if your data has been received by the server (https://github.com/nats-io/stan.js#message-acknowledgements-and-redelivery). Likewise, if the server sent you a message but the acknowledgment from the client didn't get back or didn't get back quickly enough, you'll see the message again.

**Comment by aricart** [comment]
Please feel free to reopen and add additional questions if this didn't answer your query or you have additional doubts.
