### ISSUE TITLE
'Subject must be supplied' error on automatic ack

### ISSUE THREAD

**Issue by karliky** [nats-io/stan.js#186]
Hello, dear maintainers! 😃 

We do have some intermittent errors when using STAN subscriptions.

The version of the library we are using is `"node-nats-streaming": "^0.3.2",`

The problem is that, from time to time, a 'subject must be supplied' error is thrown from the NATS library.

```
NatsError: Subject must be supplied
    at Client.handledInvalidArgs (app/node_modules/nats/lib/nats.js:1685:29)
    at Client.publish (app/node_modules/nats/lib/nats.js:1629:12)
    at Message.ack (app/node_modules/node-nats-streaming/lib/stan.js:1004:24)
    at Message.maybeAutoAck (app/node_modules/node-nats-streaming/lib/stan.js:991:10)
    at Object.callback (app/node_modules/node-nats-streaming/lib/stan.js:882:11)
    at Client.processMsg (app/node_modules/nats/lib/nats.js:1467:13)
    at Client.processInbound (app/node_modules/nats/lib/nats.js:1340:14)
    at Socket.stream.on (app/node_modules/nats/lib/nats.js:852:10)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

After researching for a bit of time, I think that on this line https://github.com/nats-io/stan.js/blob/master/lib/stan.js#L1012 the property `this.subscription.ackInbox` is undefined, therebefore the NATS.js library throws a `Subject must be supplied` error.

This is the implementation of our subscription, whose type is `setDeliverAllAvailable`:
```
    subscription.on('ready', () => {
      subscription.on('message', async (msg) => ...);
    });
    subscription.on('error', (error) => ...);
    subscription.on('unsubscribed', () => ...);
```
As you can see, we are waiting for the subscription to be ready before consuming messages.

I don't see any error, timeout, or problem raised in the connection listeners:
```
client.on('disconnect', (err) => ...);
client.on('reconnecting', () => ...);
client.on('reconnect', () => ...);
client.on('connection_lost', ...);
client.on('close', (err) => ...);
client.on('error', (err) => ...);
```

When this happens, we see a hundred errors like that raised in a few seconds, then it starts working fine again.
```
Sep 24 04:59:11 <- First Subject must be supplied is thrown
Sep 24 04:59:24 <- Last Subject must be supplied is thrown
```

I've also seen a `stan: invalid subscription` thrown a few seconds after the last error: 
```
Sep 24 04:59:29 stan: invalid subscription
```

I would say this issue is related somehow with https://github.com/nats-io/stan.js/issues/115

Could you please point me out any policy or fix we should implement? Thanks!

**Comment by aricart** [comment]
Saludos @karliky,

I have a small question - are you registering your handlers after in the connect handler?
Your code should look like:

```javascript
const STAN = require('node-nats-streaming');
const stan = STAN.connect('test-cluster', 'testid1234');
stan.on('connect', () => {
    // do everything else here.
 }
... 
```

When you connect to STAN and the `connect` handler for STAN fires, it means that the protocol for STAN has been initialized (the subjects that you are getting `subject must be supplied` have been provided by the server. 

If you create subscriptions/publish or in any way use the client before the STAN `connect` is invoked, you are prone to the error. 

#115 was filed because at some point STAN server was using different connections to respond with protocol configuration and actual message handling. This made it possible for the server to sometimes start feeding you messages before the connection that handled the protocol initialization had published a response to the client. That issue has since been fixed.

**Comment by karliky** [comment]
Yes, we are waiting for `stan.on('connect'` to be called before starting our app. I'm sorry I didn't mention that.

**Comment by renier** [comment]
Adding to what Karliky said. We are running with NATS version 2.1.7 and NATS-Streaming version 0.18.0 (which I believe has the fix @aricart mentions).

**Comment by aricart** [comment]
@renier @karliky the `stan: invalid subscription` error means that an ack or some other protocol message related to the subscription went out after the subscription was closed, can this be the case?

Can you audit where you sub#close/unsubscribe()?

One question, are your event handlers synchronous? IE do you have operations that are awaiting on promises?

**Comment by aricart** [comment]
Also check if you are closing the client - I am beginning to suspect that the client has been closed by you or some other error.

**Comment by aricart** [comment]
@renier @karliky  any updates on the questions above.

**Comment by karliky** [comment]
Hey @aricart,

The connection is created by the STAN client.

I've been reading the code again and as far I can tell, the client is not closed by any error nor us, whoever, I've done some changes to the code to add more and better logging so I can see exactly what's happening. Give me a few days so I can run the code in production to gather more information and after that, I will come back with any progress we've done.

**Comment by aricart** [comment]
@karliky what I am wondering is if you are closing the subscription from within the message notification.

**Comment by karliky** [comment]
Our operations are not awaiting on promises. I've audited the closing subscription code and as far I can tell, it's being closed correctly.

```
...
  const isConnected = utils.get(subscription, 'stanConnection.isConnected');
  if (isConnected) subscription.close();
```

**Comment by karliky** [comment]
We are seeing again this error in production with no specific pattern on why it happens. Could you please give us any advice on how to fix it or to change our implementation?

This is what happened with the last occurrence of this error:

- On `Oct 5 18:16:58` we start seeing `{"message":"Subject must be supplied","stack":"NatsError: Subject must be supplied\n    at Client.handledInvalidArgs (.../nats/lib/nats.js:1685:29)\n`. No previous errors are thrown.
- These errors appear from `Oct 5 18:16:58` to `Oct 5 18:17:01` so that's a few seconds where a ton of errors like that are thrown.
- On `Oct 5 18:17:01` a DISCONNECT is thrown by the library. Our logic tries to reconnect again and everything starts working fine again. 
```
{
    "level": 50,
    "time": 1601914621247,
    "pid": 19,
    "hostname": "5888559f69-cpxkd",
    "name": "nats",
    "data": {
        "event": "DISCONNECT",
        "stack": {
            "message": "",
            "stack": "Error\n   stack...."
        },
        "isShutingDown": false
    },
    "msg": "# Connection event captured.",
    "v": 1
}
```

Could you tell us why that `DISCONNECT` has happened or how to debug it? Why are hundreds of `NatsError: Subject must be supplied` thrown before the disconnect?

**Comment by aricart** [comment]
The disconnect is emitted because the client lost the connection to NATS. Looking into what the client does.

**Comment by aricart** [comment]
@karliky few things here, which may explain this issue.

The first thing, stan.js doesn't support promises on the callbacks. This is true for all currently released javascript clients. By providing an async handler, you are effectively marking the function as returning a promise (so the function returns), but the await condition is not resolved because the async function is yet to return. Since the library is not `awaiting` on the callback, the event loop continues, and acks the message even though you have not yet finished processing it. Immediately, the next event is processed. 

The part I am not understanding is why this is happening after the subscription emits `ready`. As at that notification happens only after the request has completed. It is as if the nats library itself was being promisified.

**Comment by aricart** [comment]
I am going to publish 0.3.3-1 to the next channel (`npm install node-nats-streaming@next`). This version does all I can do - when a message is received if the subscription response has not yet been set, the message will be dropped. This should be fine because STAN should resend that message once it detects it not acknowledged.

**Comment by aricart** [comment]
@karliky please try `npm install node-nats-streaming@next`. You shouldn't see the errors, please confirm if this works for you. Thanks.

**Comment by karliky** [comment]
Thank you so much @aricart, I will deploy that version and will come back with any progress we made. 💯

**Comment by karliky** [comment]
@aricart Hey Aricart! Sorry for the late response. Looks like your fix has fixed the issue we had, thank you so much!

**Comment by aricart** [comment]
@karliky perfect!
