### ISSUE TITLE
Invalid publish request for every publish

### ISSUE THREAD

**Issue by dagenius007** [nats-io/stan.js#189]
I keep getting invalid publish request after my nats server goes.

**Comment by kozlovic** [comment]
Please refrain from updating all closed issues from different client libraries and server.

Getting invalid publish when the server is down is expected. Can you describe better your issue?

**Comment by dagenius007** [comment]
Sorry about that @kozlovic. The server is not down. I meant after restarting my server. 

So I read this from the docs 

**`By default, the NATS Streaming Server stores its state in memory, which means that if the streaming server is stopped, all state is lost. On server restart, since no connection information is recovered, running applications will stop receiving messages and new published messages will be rejected with an invalid publish request error.`**

I don't if you can help out?

**Comment by dagenius007** [comment]
Memory store

**Comment by kozlovic** [comment]
Well, then as stated in the documentation, it is normal since the restarted server has no state and so your current connection does not exist on this server. You would need to recreate connection (and subscriptions if applicable) or use a server with file store or SQL store: https://docs.nats.io/nats-streaming-server/configuring/persistence
