### ISSUE TITLE
Reconnect when nats-streaming server close connection

### ISSUE THREAD

**Issue by dguyonvarch** [nats-io/stan.js#192]
```
nats-streaming-server version 0.19.0 with file store
node: v14.15.0
node-nats-streaming: 0.3.2
```

I try to simulate a server overload to cause the nats-streaming server to close the connection. 
I just wait with a `debugger` to force the closing.

```javascript
const natsStreaming = require('node-nats-streaming');
const sc = natsStreaming.connect('test-cluster', 'test', { waitOnFirstConnect: true });
sc.on('connect', () => {
  console.log('[NATS] connect');

  // emitted whenever the client disconnects from a server
  sc.on('disconnect', () => {
    console.log('[NATS] disconnect');
  });

  // emitted whenever the client is attempting to reconnect
  sc.on('reconnecting', () => {
    console.log('reconnecting');
  });

  // emitted whenever the client reconnects
  // reconnect callback provides a reference to the connection as an argument
  sc.on('reconnect', () => {
    console.log(`[NATS] reconnect`);
  });

  // emitted when the connection is closed - once a connection is closed
  // the client has to create a new connection.
  sc.on('close', function() {
    console.log('[NATS] close');
  });

  // emitted whenever the server returns a permission error for
  // a publish/subscription for the current user. This sort of error
  // means that the client cannot subscribe and/or publish/request
  // on the specific subject
  sc.on('permission_error', function(err) {
    console.error('[NATS] got a permissions error', err.message);
  });

  sc.on('connection_lost', async (error) => {
    console.log('disconnected from stan', error);
  });
  sc.on('error', (error) => {
    console.log('[Nats] error', error);
  });

  debugger;
  setTimeout(() => {
    // Simple Publisher (all publishes are async in the node version of the client)
    sc.publish('foo', 'Hello node-nats-streaming!', (err, guid) => {
      if (err) {
        console.log('publish failed: ' + err);
      } else {
        console.log('published message with guid: ' + guid);
      }
    });
  });
});
```
when the connection is closed (I keep watch with the api http://localhost:8222/streaming/clientsz), i continue the debugger.

This is the console ouput:
```     
[NATS] connect
..... Wait for the connection to close with debugger instruction then continue....
[NATS] disconnect
reconnecting
[NATS] reconnect
publish failed: client has been replaced or is no longer registered
disconnected from stan client has been replaced or is no longer registered
[NATS] close
```   

Why does the `publish` fail when the stan connection is reconnected ?

**Comment by kozlovic** [comment]
@dguyonvarch What you caused is for the server to close the client connection because of the lack of heartbeat responses from the client library. Once the server closes the connection, the client must recreate it. No streaming library currently does that for you. What you have seen is the NATS connection being able to reconnect, but the streaming connection (see it more as a session) is lost and needs to be recreated, along with its subscription.
See [this](https://docs.nats.io/nats-streaming-concepts/client-connections#note-important-things-to-know-about-reconnections) for more information.

**Comment by dguyonvarch** [comment]
@kozlovic Thanks you for your fast reply. 
What is the best way to manage reconnexion. With the 'connection_lost' handler ? I try this but it seems that `publish` is sent before the new connection is created.

PS: when nats-streaming server is stoped, 'connection_lost' is also triggered but with the error: `connection lost due to PING failure`. I don't want to manage a new connexion in this case. Is there any way to find the error type (with a specialized error or an error number) ? Juste testing the message is a little tricky :wink:

**Comment by kozlovic** [comment]
> What is the best way to manage reconnexion. With the 'connection_lost' handler ?

Yes, if the connection lost handler is invoked it means the streaming connection (again, see this more like a session) is no longer valid and needs to be recreated, along with all the subscriptions (if applicable).

> I try this but it seems that publish is sent before the new connection is created.

You should always expect that a publish can fail. Handling of connection lost will not change that.

> when nats-streaming server is stoped, 'connection_lost' is also triggered but with the error: connection lost due to PING failure.

Correct. In this case, it is the library itself that closes the connection because the server is not responding to the client-to-server PINGs. But result is the same, the connection need to be recreated. Note that if you want the application to survive longer period with no access to the streaming server, you should increase the interval/max ping configuration in the client. 

> I don't want to manage a new connexion in this case. Is there any way to find the error type (with a specialized error or an error number) ? Juste testing the message is a little tricky

There is no code that I am aware of. So you would have to look at the error string and differentiate indeed between the two conditions.
